Contactus1/Models/Message.cs
using System.ComponentModel.DataAnnotations;

namespace Contactus1.Models
{
    public class Message
    {
        [Display(Name= "نام و نام خانوادگی")]
        [Required(ErrorMessage ="{0} را وارد کنید")]
        public string FullName { get; set; }
        [Display(Name = "موضوع پیام")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string Subject { get; set; }
        [Display(Name = "شماره تماس")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        [MaxLength(11,ErrorMessage ="نامعتبر است {0}")]
        public string PhoneNumber { get; set; }
        [Display(Name = "متن پیام")]
        [Required(ErrorMessage = "{0} را وارد کنید")]
        public string MessageBody { get; set; }
        //[DataType(DataType.Password)]
        //public int COde { get; set; }

        //confirm phoneNumber Or Password
        //[Display(Name ="تکرار شماره تماس")]
        //[Required(ErrorMessage = "{0} را وارد کنید")]
        //[MaxLength(11)]

        //[Compare("PhoneNumber",ErrorMessage ="شماره موبایل یکسان نیست ")]
        //public int confirmPhoneNumber { get; set; }

    }

}

Contactus1/Controllers/HomeController.cs
using Contactus1.DataBase;
using Contactus1.Models;
using Microsoft.AspNetCore.Mvc;

namespace ContactForm_US.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index(int id)
        {
            ViewBag.message = id;
            ViewData["Message2"] = "Amirhossein";
            TempData["Message3"] = "Mokhtari";
            return View();
        }

        [HttpGet("/codeYad/Privacy/{name}/{id:int}")]
        public IActionResult Privacy(string name, int id, string address)
        {
            return View(model: name);
        }

        public IActionResult Messages()
        {
            return View(DataBase.Messagess);

        }

        [HttpPost]
        public IActionResult SendMessage(Message message)
        {
            if(!ModelState.IsValid)
            {
                return View("index", message);
            }
            if (message.PhoneNumber.Length == 11)
            {
                TempData["IsSuccess"] = true;
                DataBase.Messagess.Add(message);
            }
              
            return Redirect("/home/Messages");
        }
    }
}

Contactus1/ViewComponents/MessagesViewComponent.cs
using System.Threading.Tasks;
using Contactus1.DataBase;
using Microsoft.AspNetCore.Mvc;

namespace ContactUs.ViewComponents
{
    public class MessagesViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult(View("TableMessage",DataBase.Messagess));
        }
    }
}

Contactus1/Views/Home/Index.cshtml
@model Contactus1.Models.Message
@{
    ViewData["Title"] = "ثبت پیام";
    var message = ViewBag.message.ToString();
    var message2 = ViewData["Message2"];

}
<div class="container-login100" style="background-image:url('/images/bg-01.jpg');">
    <div class="wrap-login100 p-l-55 p-r-55 p-t-65 p-b-54">
        <form method="post" action="/home/SendMessage" class="login100-form validate-form">
            <div asp-validation-summary="All"></div>
            <span class="login100-form-title p-b-49">
                تماس با ما @ViewBag.message
            </span>
            @* <input asp-for="COde" class="form-control" />*@
            @* <div class="alert alert-success">
            ViewBag  @message
            </div>
            <div class="alert alert-danger">
            ViewData  @message2
            </div>*@
            @*
            <div class="alert alert-danger">
            TempData   @message3
            </div>*@

            <div class="wrap-input100 validate-input m-b-23">
                <label asp-for="FullName" class="label-input100"></label>
                <input asp-for="FullName" autocomplete="off" class="input100" type="text" placeholder="نام خود را وارد کنید">
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>

            <div class="wrap-input100 validate-input m-b-23">
                <label asp-for="Subject" class="label-input100"></label>
                <input asp-for="Subject" autocomplete="off" class="input100" type="text" placeholder="موضوع پیام خورد را بنویسید">
                <span asp-validation-for="Subject" class="text-danger"></span>

            </div>
            <div class="wrap-input100 validate-input m-b-23">
                <label asp-for="PhoneNumber" class="label-input100"></label>
                <input asp-for="PhoneNumber" autocomplete="off" class="input100" type="text" placeholder="شماره تماس خود را وارد کنید">
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            @* <div class="wrap-input100 validate-input m-b-23">
            <label asp-for="confirmPhoneNumber" class="label-input100"></label>
            <input asp-for="confirmPhoneNumber" autocomplete="off" class="input100" type="text" placeholder="شماره تماس خود را وارد کنید">
            <span asp-validation-for="confirmPhoneNumber" class="text-danger"></span>
            </div>*@
            <div class="wrap-input100 validate-input m-b-23">
                <label asp-for="MessageBody" class="label-input100"></label>
                <textarea asp-for="MessageBody" autocomplete="off" class="input100" type="text" placeholder="پیام خود را در این قسمت بنویسد">
                        </textarea>
                <span asp-validation-for="MessageBody" class="text-danger"></span>
            </div>
            <div class="container-login100-form-btn mt-4">
                <div class="wrap-login100-form-btn">
                    <div class="login100-form-bgbtn"></div>
                    <button type="submit" class="login100-form-btn">
                        ارسال
                    </button>
                </div>
            </div>
            @* RouteConfig*@
            @*<a class="btn btn-success" href="@Url.Action(action:"Messages",controller:"Home")">Send</a>*@
        </form>
    </div>
</div>



@section Scripts
    {
    <script src="/jquery-validation/dist/jquery.validate.min.js"></script>
    <script src="/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
}

Contactus1/Views/Home/Messages.cshtml
@using Contactus1.Models;
@model List<Contactus1.Models.Message>
@{
    ViewData["Title"] = "پیام ها";
    var counter = 1;
    var message3 = TempData["IsSuccess"];
    var partialView = new List<Message>()
    {
        new Message()
        {
            FullName="امیرحسین مختاری",
            PhoneNumber="09224940113",
            MessageBody="خوبی..",
            Subject="تشکر.."
        }
    };
 

}
@section Style
    {

    <style>
        thead th {
            text-align: right;
        }

        thead {
            box-shadow: 0 0 2px 0 gray;
            background: #0000000d;
        }

        body {
            background-image: url('/images/bg-01.jpg');
            background-size: cover;
        }
    </style>
}
<div class="container">
    <div class="card">
        <div class="card-header">
            لیست پیام ها
        </div>

        @if (message3 != null)
        {
            <div class="alert alert-success">
                عملیات با موفقیت انجام شد
            </div>
        }
        else
        {
            <div class="alert alert-success">
                Eror
            </div>
        }
        <div class="card-body">
            @*<partial name="_Message" />*@
            @await Component.InvokeAsync("Messages");
        </div>
        <div class="card-body">
            @await Html.PartialAsync("_Message",partialView);
        </div>
    </div>
</div>

Contactus1/Views/Shared/Components/Messages/TableMessage.cshtml
@model List<Contactus1.Models.Message>
@{
    var counter = 1;
}

<table class="table table-bordered text-center">
    <thead>
        <tr>
            <th>#</th>
            <th>عنوان</th>
            <th>شماره تماس</th>
            <th>نام و نام خانوادگی</th>
            <th>پیام</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>@counter</td>
                <td>@item.Subject</td>
                <th>
                    <call phone-number="@item.PhoneNumber"></call>
                </th>
                <td>@item.FullName</td>
                <td>@item.PhoneNumber</td>
            </tr>
            counter = +1;
        }
    </tbody>

</table>

Contactus1/Views/Shared/_ContactLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>@ViewData["Title"]</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="images/icons/favicon.ico" />
    <partial name="_MetaCssLinks"/>

    @await RenderSectionAsync("Style", false)
</head>

<body dir="rtl">
    <div class="limiter">
        @RenderBody()
    </div>

    <div id="dropDownSelect1"></div>
    <script src="/vendor/jquery/jquery-3.2.1.min.js"></script>
    <script src="/vendor/animsition/js/animsition.min.js"></script>
    <script src="/vendor/bootstrap/js/popper.js"></script>
    <script src="/vendor/bootstrap/js/bootstrap.min.js"></script>
    <script src="/vendor/select2/select2.min.js"></script>
    <script src="/vendor/daterangepicker/moment.min.js"></script>
    <script src="/vendor/daterangepicker/daterangepicker.js"></script>
    <script src="/vendor/countdowntime/countdowntime.js"></script>
    <script src="/js/main.js"></script>
    @await RenderSectionAsync("Scripts", false)
</body>
</html>

Contactus1/Views/Shared/_Message.cshtml
@model List<Contactus1.Models.Message>
@{
    var counter = 1;
}

<table class="table table-bordered text-center">
    <thead>
        <tr>
            <th>#</th>
            <th>عنوان</th>
            <th>شماره تماس</th>
            <th>نام و نام خانوادگی</th>
            <th>پیام</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {

            <tr>
                <td>@counter</td>
                <td>@item.Subject</td>
                <th>
                    <call phone-number="@item.PhoneNumber"></call>
                </th>
                <td>@item.FullName</td>
                <td>@item.PhoneNumber</td>
            </tr>
            counter = +1;
        }
    </tbody>

</table>

Contactus1/Views/Shared/_MetaCssLinks.cshtml
<link rel="stylesheet" type="text/css" href="/vendor/bootstrap/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/fonts/font-awesome-4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/fonts/iconic/css/material-design-iconic-font.min.css">
<link rel="stylesheet" type="text/css" href="/vendor/animate/animate.css">
<link rel="stylesheet" type="text/css" href="/vendor/css-hamburgers/hamburgers.min.css">
<link rel="stylesheet" type="text/css" href="/vendor/animsition/css/animsition.min.css">
<link rel="stylesheet" type="text/css" href="/vendor/select2/select2.min.css">
<link rel="stylesheet" type="text/css" href="/vendor/daterangepicker/daterangepicker.css">
<link rel="stylesheet" type="text/css" href="/css/util.css">
<link rel="stylesheet" type="text/css" href="/css/main.css">